# Generated by Django 4.2.1 on 2023-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amistad_id', models.IntegerField(blank=True, null=True)),
                ('texto', models.CharField(max_length=50)),
            ],
        ),
    ]
