# Generated by Django 4.2.1 on 2023-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=200)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='fecha publicado')),
            ],
        ),
    ]
