# Generated by Django 4.2.1 on 2023-11-18 02:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='fecha publicado')),
            ],
        ),
        migrations.CreateModel(
            name='Userdador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usertario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=200)),
                ('municipio', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='fecha publicado')),
                ('latitud', models.CharField(blank=True, max_length=42)),
                ('longitud', models.CharField(blank=True, max_length=42)),
                ('usertario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=24, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='fecha publicado')),
                ('amistad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.amistad')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_renta', models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='gallery')),
                ('name_foto_renta', models.CharField(max_length=200)),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.renta')),
            ],
        ),
        migrations.AddField(
            model_name='amistad',
            name='userdador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.userdador'),
        ),
        migrations.AddField(
            model_name='amistad',
            name='usertario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
