# Generated by Django 4.2.1 on 2023-11-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdador',
            name='tipo',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='usertario',
            name='tipo',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
