# Generated by Django 4.2.1 on 2023-11-18 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amistad',
            name='usertario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.usertario'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='usertario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.usertario'),
        ),
    ]
