# Generated by Django 4.2.1 on 2023-05-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_renta', models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='rentapp')),
                ('name_foto_renta', models.CharField(max_length=200)),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.renta')),
            ],
        ),
    ]
