# Generated by Django 4.2.1 on 2024-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renta',
            old_name='usertario',
            new_name='user',
        ),
    ]
