# Generated by Django 4.2.1 on 2023-07-18 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='latitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renta',
            name='longitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
    ]
