# Generated by Django 4.2.1 on 2025-01-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_rename_usertario_renta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renta',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='renta',
            name='referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
