# Generated by Django 4.2.1 on 2023-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_userdador_tipo_usertario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertario',
            name='categoria',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('abogado', 'Abogado'), ('empresa', 'Empresa o Compañia')], default='propietario', max_length=24),
        ),
    ]
