# Generated by Django 4.2.1 on 2023-11-28 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_usertario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistad',
            name='renta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.renta'),
        ),
    ]
