# Generated by Django 4.2.1 on 2023-09-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_renta_latitud_renta_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail_UserArio', models.EmailField(max_length=254)),
                ('telefono_UserArio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.user'),
        ),
    ]
