# Generated by Django 4.2.1 on 2025-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_remove_renta_latitud_remove_renta_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Tipo'),
        ),
    ]
