# Generated by Django 4.2.1 on 2023-09-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_user_renta_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
