# Generated by Django 4.2.1 on 2023-09-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_rename_fotos_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('amistad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.amistad')),
            ],
        ),
        migrations.CreateModel(
            name='Userdador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usertario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='renta',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='amistad',
            name='userdador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.userdador'),
        ),
        migrations.AddField(
            model_name='amistad',
            name='usertario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.usertario'),
        ),
        migrations.AddField(
            model_name='renta',
            name='usertario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentapp.usertario'),
        ),
    ]
