# Generated by Django 4.2.1 on 2023-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_remove_renta_e_mail_remove_renta_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image_renta',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='pub_date',
            field=models.TimeField(verbose_name='fecha publicado'),
        ),
    ]
