# Generated by Django 4.2.1 on 2023-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0008_alter_foto_image_renta_alter_renta_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='pub_date',
            field=models.DateTimeField(verbose_name='fecha publicado'),
        ),
    ]
