# Generated by Django 4.2.1 on 2024-11-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0008_userdador_tipo_usertario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='usertario',
            name='tipo',
        ),
    ]
