# Generated by Django 4.2.1 on 2023-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0009_alter_renta_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistad',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='fecha publicado'),
        ),
        migrations.AddField(
            model_name='amistad',
            name='relacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
