# Generated by Django 4.2.1 on 2023-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0011_alter_renta_latitud_alter_renta_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='latitud',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='renta',
            name='longitud',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
