# Generated by Django 4.2.1 on 2023-10-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0013_renta_municipio_renta_provincia_renta_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='fecha publicado'),
        ),
    ]
