# Generated by Django 4.2.1 on 2023-10-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0014_mensaje_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
